#!/bin/bash

#enter username here

username=$(whiptail --inputbox "Enter Username" 8 39 --title "ADD USER" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]; then

###Check existence of user###
getent passwd $username &>/dev/null
if [ $? -eq 0 ] 
then
whiptail --title "OOPS" --msgbox "User $username is already existed please enter another one OR Invalid Input" 8 78
./menu
else
sudo useradd $username &> /dev/null
password=$(whiptail --passwordbox "Enter User Password" 8 39 --title "ADD USER" 3>&1 1>&2 2>&3)
echo $password | sudo passwd $username  --stdin &>/dev/null
whiptail --title "DONE" --msgbox "User $username is added successfully" 8 78
./menu
fi

else
    ./menu
fi
