#!/bin/bash

groupname=$(whiptail --inputbox "Enter a group name" 8 39 --title "ADD GROUP" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]; then

sudo getent group $groupname &>/dev/null
if [ $? -eq 0 ] 
then
whiptail --title "OOPS" --msgbox "Group $groupname is already existed please enter another one" 8 78
./menu
else
sudo groupadd $groupname &> /dev/null
whiptail --title "DONE" --msgbox "Group $groupname is created successfully" 8 78
./menu
fi

else
    ./menu
fi
