#!/bin/bash

username=$(whiptail --inputbox "Enter a user" 8 39 --title "Change Password" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]; then
sudo id $username &> /dev/null

if [ $? -eq 0 ] 
then
password=$(whiptail --passwordbox "Enter User Password" 8 39 --title "Change Password" 3>&1 1>&2 2>&3)
echo $password | sudo passwd $username  --stdin &>/dev/null
whiptail --title "DONE" --msgbox "Password changed successfully" 8 78
./menu

else
whiptail --title "OOPS" --msgbox "User $username is not existed" 8 78
./menu
fi

else
 ./menu
fi

