#!/bin/bash

groupname=$(whiptail --inputbox "Enter a group you want to delete" 8 39 --title "Delete Group" 3>&1 1>&2 2>&3)
# A trick to swap stdout and stderr.
# Again, you can pack this inside if, but it seems really long for some 80-col terminal users.

exitstatus=$?
if [ $exitstatus = 0 ]; then
sudo getent group $groupname &> /dev/null
if [ $? -eq 0 ] 
then
sudo groupdel $groupname &> /dev/null
whiptail --title "Done" --msgbox "Group $groupname is deleted successfully" 8 78
./menu
else
whiptail --title "OOPS" --msgbox "Group $groupname is not existed" 8 78
./menu
fi

else
 ./menu
fi

