#!/bin/bash

shell=$(whiptail --inputbox "Enter user shell\n ex:/sbin/nologin" 8 39 --title "User Modify" 3>&1 1>&2 2>&3)

exitstatus=$?
if [ $exitstatus = 0 ]; then
sudo usermod -s "$shell" $username
whiptail --title "DONE" --msgbox "Shell $shell is set to user $username" 8 78
 ./menu
else
    ./menu
fi

